"""IATA airline codes to English names, so offers from different sources match."""

from __future__ import annotations

NAMES: dict[str, str] = {
    # UK <-> China direct
    "BA": "British Airways",
    "VS": "Virgin Atlantic",
    "CA": "Air China",
    "MU": "China Eastern",
    "CZ": "China Southern",
    "HU": "Hainan Airlines",
    "3U": "Sichuan Airlines",
    "GS": "Tianjin Airlines",
    "FM": "Shanghai Airlines",
    "HO": "Juneyao Air",
    "MF": "Xiamen Airlines",
    "ZH": "Shenzhen Airlines",
    "CX": "Cathay Pacific",
    "PN": "West Air",
    "8L": "Lucky Air",
    "JD": "Capital Airlines",
    "KN": "China United",
    "GJ": "Loong Air",
    "EU": "Chengdu Airlines",
    "SC": "Shandong Airlines",
    "G5": "China Express",
    "QW": "Qingdao Airlines",
    "9C": "Spring Airlines",
    "TV": "Tibet Airlines",
    "DZ": "Donghai Airlines",
    "HX": "Hong Kong Airlines",
    "UO": "HK Express",
    "BR": "EVA Air",
    "CI": "China Airlines",
    "MS": "EgyptAir",
    "SN": "Brussels Airlines",
    "WY": "Oman Air",
    "GF": "Gulf Air",
    "UL": "SriLankan",
    "AI": "Air India",
    "PK": "PIA",
    "HY": "Uzbekistan Airways",
    "KC": "Air Astana",
    "TG": "Thai Airways",
    "VN": "Vietnam Airlines",
    "MH": "Malaysia Airlines",
    # common one-stop carriers
    "AY": "Finnair",
    "KL": "KLM",
    "AF": "Air France",
    "LH": "Lufthansa",
    "LX": "Swiss",
    "OS": "Austrian",
    "SK": "SAS",
    "TK": "Turkish Airlines",
    "EK": "Emirates",
    "QR": "Qatar Airways",
    "EY": "Etihad",
    "SQ": "Singapore Airlines",
    "KE": "Korean Air",
    "OZ": "Asiana",
    "JL": "Japan Airlines",
    "NH": "ANA",
    "LO": "LOT Polish",
    "AZ": "ITA Airways",
    "IB": "Iberia",
    "EI": "Aer Lingus",
    "SU": "Aeroflot",
    "U2": "easyJet",
    "FR": "Ryanair",
    "W6": "Wizz Air",
    "VY": "Vueling",
}


def name(code: str, fallback: str = "") -> str:
    return NAMES.get(code.upper(), fallback or code.upper())
